# Generated by Django 5.0.14 on 2026-08-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur', models.CharField(max_length=255)),
                ('taille', models.CharField(max_length=100)),
                ('contexte_additionnel', models.TextField(blank=True)),
                ('contact_nom', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
