# Generated by Django 5.0.14 on 2026-08-18 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('direction', 'Direction générale'), ('rh', 'Ressources humaines'), ('comptabilite', 'Comptabilité / Finance'), ('it', 'Informatique'), ('commercial', 'Commercial / Ventes'), ('juridique', 'Juridique'), ('marketing', 'Marketing / Communication'), ('production', 'Production / Opérations'), ('achats', 'Achats / Logistique'), ('autre', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('active', 'Active'), ('terminee', 'Terminée')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('perimetre_valide', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioPhishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_email', models.CharField(max_length=255)),
                ('corps_email', models.TextField()),
                ('url_fausse_page', models.URLField()),
                ('secteur_cible', models.CharField(max_length=255)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='campagnes.campagne')),
            ],
        ),
    ]
